#base image - nginx with lag latest
FROM nginx:latest

#Adding custom index.html hosted on Github
ADD https://raw.githubusercontent.com/erezrozenbaum/sharedrepo/main/My-Green-App.html /usr/share/nginx/html/

#Adding read permissions to custome index.html
RUN chmod +r /usr/share/nginx/html/index.html

# 'nginx -g daemom off' will run as default command when any container is run that uses the image that was built using this Dockerfile
CMD ["nginx", "-g", "daemon off;"]